- name: Add RabbitMQ team main signing key
  apt_key:
    keyserver: hkps://keys.openpgp.org
    id: 0x0A9AF2115F4687BD29803A206B73A36E6026DFCA
    state: present

- name: Add Launchpad PPA key (Erlang releases)
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: F77F1EDA57EBB1CC
    state: present

- name: Add RabbitMQ team main signing key
  apt_key:
    url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    state: present

- name: Add apt repository for RabbitMQ
  apt_repository:
    repo: "deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ bionic main"
    filename: rabbitmq_erlang
    update_cache: no

- name: Add apt repository for Erlang
  apt_repository:
    repo: "deb http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu bionic main"
    filename: rabbitmq_main
    update_cache: yes

# - name: Set package erlang preference
#   copy:
#     dest: /etc/apt/preferences.d/erlang
#     content: |
#       Package: erlang*
#       Pin: release o=Bintray
#       Pin-Priority: 1000

- name: Pin RabbitMQ version
  copy:
    dest: /etc/apt/preferences.d/rabbitmq
    content: |
      Package: rabbitmq-server
      Pin: version {{ rabbitmq_version }}
      Pin-Priority: 1002
  when: rabbitmq_pin_version | bool == True

- name: Install RabbitMQ
  apt:
    name: "rabbitmq-server={{ rabbitmq_version }}"
    state: present
    # Prevent Rabbit from starting immediately after installation before we could apply custom config (including clustering)
    policy_rc_d: 101 # 101 means "action forbidden by policy"
